var settings = 
{
   "version":"0210.024",
   "rtuId":2,
   "description":"SiteOne2",
   "timeZone":2,
   "fixedTxTime":2,
   "commsTimeout":30,
   "localwebserver":{
      "ipAddress":"192.168.1.224",
      "port":8010,
      "socketPort":0,
      "defaultHtmlPage":"index.html"
   },
   "modbusslave":{
      "enabled":1,
      "port":2030
   },
   "remotewebserver":{
      "ipAddress":"192.168.1.224",
      "port":12345
   },
   "control":[
      {
         "id":1,
         "controlType":"reservoir",
         "description":"Control Pumps at site1",
         "setPoints":{
            "low":"19",
            "hi":"30",
            "sourceIO":"2",
            "io":"AI1Scaled"
         },
         "msgOutSetPointLow":{
            "sourceAddress":1,
            "destinationAddress":2,
            "msgType":"control",
            "write":{
               "destinationIO":"1",
               "io":"digOut",
               "mask":"1",
               "value":"255"
            }
         },
         "msgOutSetPointHi":{
            "sourceAddress":1,
            "destinationAddress":2,
            "msgType":"control",
            "write":{
               "destinationIO":"1",
               "io":"digOut",
               "mask":"1",
               "value":"0"
            }
         },
         "enabled":false
      }
   ],
   "io":[
      {
         "id":1,
         "ioType":"TCP-MODMUX-DIO8",
         "enabled":1,
         "ipAddress":"192.168.1.11",
         "port":502,
         "description":"Site1One DIO",
         "unitid":0,
         "registertype":"readCoils",
         "startAddress":10,
         "endAddress":10,
         "readMask":65535,
         "writeMask":0,
         "value":67
      },
      {
         "id":2,
         "ioType":"TCP-MODMUX-AI8",
         "enabled":1,
         "ipAddress":"192.168.1.10",
         "port":502,
         "description":"Site1 AI",
         "unitid":0,
         "registertype":"readCoils",
         "startAddress":11,
         "endAddress":11,
         "readMask":1,
         "writeMask":0,
         "value":65535,
         "scaling":[
            {
               "id":1,
               "description":"AI1",
               "rawHi":"10001",
               "rawLow":0,
               "scaleHi":100,
               "scaleLow":0
            },
            {
               "id":2,
               "description":"AI2",
               "rawHi":10000,
               "rawLow":0,
               "scaleHi":100,
               "scaleLow":0
            }
         ],
         "cofs":[
            {
               "description":"AI1",
               "value":5
            },
            {
               "description":"AI2",
               "value":5
            }
         ]
      },
      {
         "id":3,
         "ioType":"GAR-FEP",
         "enabled":0,
         "commPort":"COM33",
         "baudRate":9600,
         "description":"GAR Front End",
         "unitid":0
      }
   ]
}